/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as helloSwtrSol from "./Hello_swtr.sol";
export type { helloSwtrSol };
import type * as helloSwtr2Sol from "./Hello_swtr2.sol";
export type { helloSwtr2Sol };
import type * as iperc20MetadataSol from "./IPERC20Metadata.sol";
export type { iperc20MetadataSol };
import type * as myErc721Sol from "./MyERC721.sol";
export type { myErc721Sol };
import type * as perc721SampleSol from "./PERC721Sample.sol";
export type { perc721SampleSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
import type * as transparentUpgradeableProxySol from "./TransparentUpgradeableProxy.sol";
export type { transparentUpgradeableProxySol };
export type { ERC721 } from "./ERC721";
export type { IPERC20 } from "./IPERC20";
export type { PERC20 } from "./PERC20";
export type { PERC20Sample } from "./PERC20Sample";
export type { ProxyAdmin } from "./ProxyAdmin";
